// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  learnSidebar: [{ type: 'autogenerated', dirName: 'Learn' }],
  buildSidebar: [{ type: 'autogenerated', dirName: 'Build' }],
  finalitySidebar: [{ type: 'autogenerated', dirName: 'Finality' }],

};

module.exports = sidebars;
